# Generated by Django 4.0.4 on 2022-06-21 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientes',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pacientes'),
        ),
        migrations.AddField(
            model_name='productos',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='productos'),
        ),
        migrations.AddField(
            model_name='productos',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='servicios',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
