# Generated by Django 4.0.4 on 2022-06-23 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0002_pacientes_image_productos_image_productos_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pacientes',
            options={'verbose_name': 'paciente', 'verbose_name_plural': 'pacientes'},
        ),
        migrations.AlterModelOptions(
            name='productos',
            options={'verbose_name': 'producto', 'verbose_name_plural': 'productos'},
        ),
        migrations.AlterModelOptions(
            name='servicios',
            options={'verbose_name': 'servicio', 'verbose_name_plural': 'servicios'},
        ),
    ]
