# Generated by Django 4.0.4 on 2022-06-23 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0003_alter_pacientes_options_alter_productos_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicios',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='servicios'),
        ),
    ]
