# Generated by Django 4.0.4 on 2022-07-02 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0004_servicios_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacientes',
            name='image',
        ),
    ]
